/* 
   Sketch generated by the Arduino IoT Cloud Thing "Untitled"
   https://create.arduino.cc/cloud/things/6311cd93-661f-4d2e-ac78-528097ee1f5a 

   Arduino IoT Cloud Variables description

   The following variables are automatically generated and updated when changes are made to the Thing

   float humidity;
   float temeprature;
   bool led;

   Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
   which are called when their values are changed from the Dashboard.
   These functions are generated with the Thing and added at the end of this sketch.
 */

 #include "thingProperties.h"
 #include "DHT.h"
 #define DHTPIN 7
 #define DHTTYPE DHT22 // DHT22 

 DHT dht(DHTPIN , DHTTYPE);

 void setup() {
   // Initialize serial and wait for port to open:
   Serial.begin(9600);
   // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
   pinMode(LED_BUILTIN, OUTPUT);
   // Defined in thingProperties.h
   initProperties();
   dht.begin();

   // Connect to Arduino IoT Cloud
   ArduinoCloud.begin(ArduinoIoTPreferredConnection);

   /*
      The following function allows you to obtain more information
      related to the state of network and IoT Cloud connection and errors
      the higher number the more granular information you’ll get.
      The default is 0 (only errors).
      Maximum is 4
  */
   setDebugMessageLevel(2);
   ArduinoCloud.printDebugInfo();
 }

 void loop() {
   ArduinoCloud.update();


   temeprature  = dht.readTemperature();


   delay(1000);
   // waiting for 30 seconds 



 }





 /*
   Since Led is READ_WRITE variable, onLedChange() is
   executed every time a new value is received from IoT Cloud.
 */
 void onLedChange()  {
   digitalWrite(LED_BUILTIN, led); 
   // Add your code here to act upon Led change
 }
